export const POSITIVE_WORDS = [
  "trusted",
  "trustworthy",
  "reliable",
  "reputable",
  "leading",
  "leader",
  "excellent",
  "innovative",
  "top choice",
  "top-rated",
  "recommended",
  "strong reputation",
  "well-regarded",
  "respected",
  "praised",
  "quality",
  "consistent",
  "outstanding",
  "best",
  "trusted name",
];

export const NEGATIVE_WORDS = [
  "scandal",
  "controversy",
  "controversial",
  "complaint",
  "complaints",
  "unreliable",
  "criticized",
  "criticism",
  "poor",
  "declining",
  "distrust",
  "lawsuit",
  "fraud",
  "concerns",
  "negative feedback",
  "untrustworthy",
  "risky",
  "warning",
  "penalized",
  "fined",
];
